app/todo/forms.py
from flask_wtf import FlaskForm, widgets
from wtforms import StringField, BooleanField, SubmitField, TextAreaField, SelectMultipleField
from wtforms.validators import ValidationError, DataRequired, EqualTo, Length
from app.models import User

class TaskForm(FlaskForm):
	task = TextAreaField('Your task name', validators=[DataRequired(), Length(min=1, max=50)])
	submit = SubmitField('Submit')

class SubtaskForm(FlaskForm):
	subtask = TextAreaField('', validators=[DataRequired(), Length(min=1, max=50)],description='Add your subtasks')
	submit = SubmitField('Add')

class SubtaskCompletionForm(FlaskForm):
	status = BooleanField('')
	#submit = SubmitField('Sign In')

app/todo/__init__.py
from flask import Blueprint

bp = Blueprint('todo',__name__)

from app.todo import routes

app/todo/routes.py
from app import db
from flask import render_template, flash, redirect, url_for, request, current_app
from app.todo.forms import TaskForm, SubtaskForm, SubtaskCompletionForm
from app.models import User, Task, Subtask
from app.todo import bp
from flask_login import current_user, login_user, login_required, logout_user
from werkzeug.urls import url_parse
import datetime
import dateutil.relativedelta as rel

@bp.route('/tasks', methods=['GET', 'POST'])
@login_required
def tasks():
	form = TaskForm()
	if form.validate_on_submit():
		task = Task(name=form.task.data, doer=current_user)
		db.session.add(task)
		db.session.commit()
		flash('Your task is added!')
		return redirect(url_for('todo.tasks'))

	#getting days left
	weekdays={0:'Monday',1:'Tuesday',2:'Wednesday',3:'Thursday',4:'Friday',5:'Saturday',6:'Sunday'}
	today=datetime.date.today()
	weekday=datetime.date.weekday(today)
	days_left = 7-weekday
	weekday=weekdays[weekday]
	#Getting all tasks for the current_user
	weekly_tasks = Task.query.filter(Task.user_id == current_user.id, Task.n_subtasks>0, Task.challenge==None)
	daily_tasks = Task.query.filter(Task.user_id == current_user.id, Task.n_subtasks == 0,Task.challenge==None)
	challenge_tasks = Task.query.filter(Task.doer == current_user, Task.challenge_id>0, Task.status == 'Active pending')
	return  render_template('todo/tasks_home.html', title='Home', today=today, days_left=days_left, weekday=weekday,form=form,daily_tasks = daily_tasks, weekly_tasks = weekly_tasks, challenge_tasks=challenge_tasks)

@bp.route('/task/<id>', methods=['GET', 'POST'])
@login_required
def task(id):
	#Adding a new subtask
	form = SubtaskForm()
	task = Task.query.filter_by(id=id).first()
	if form.validate_on_submit():
		subtask = Subtask(name=form.subtask.data, task=task)
		task.n_subtasks+=1
		db.session.add(subtask)
		db.session.commit()
		flash('Your subtask is added!')
		return redirect(url_for('todo.task',id=id))

	#Getting completed subtasks via checkboxes
	if request.method=='POST':
		checked_ids=request.form.getlist('status_checkbox')
		all_subtasks=Subtask.query.filter_by(task_id=id)
		for subtask in all_subtasks:
			if str(subtask.id) in checked_ids:
				subtask.check()
			else:
				subtask.uncheck()
		return redirect(url_for('todo.task', id=id))
	#checked_subtasks, unchecked_subtasks
	uc_subtasks = Subtask.query.filter_by(task_id=id, status=0)
	c_subtasks = Subtask.query.filter_by(task_id=id, status=1)
	return render_template('todo/task.html', form=form, task = task, c_subtasks = c_subtasks, uc_subtasks=uc_subtasks)


@bp.route('/delete_task/<id>')
@login_required
def delete_task(id):
	Subtask.query.filter_by(task_id = id).delete()
	Task.query.filter_by(id = id).delete()
	db.session.commit()
	flash('Task deleted successfully')
	return redirect(url_for('todo.tasks'))

@bp.route('/update_challenge/<id>')
@login_required
def update_challenge(id):
	task=Task.query.filter_by(id = id).first_or_404()
	if task.status=='Active pending':
		task.set_status('Active on track')
		task.change_streak(1)
		flash('Congratulations! You are on track.')
		redirect(ur_for('todo.tasks'))
	redirect(ur_for('todo.tasks'))

app/templates/todo/_challenge_task_display.html
<div class="card" style="height:3.8em; padding:1em; width:32.6%;border-style:none; margin:0.1em; background-color:#fff; display:flex; flex-direction:row;
justify-content: space-around">
  <a href="{{ url_for('todo.update_challenge', id=task.id) }}"><input type='checkbox' class='checkbox'></input></a>
  <a href="{{ url_for('todo.task', id=task.id) }}"><p><b>{{ task.name }}{{ task.get_streak() }}{{ task.status }}</b></p> </a>
</div>

app/templates/todo/_daily_task_display.html
<div class="card" style="height:3.8em; padding:1em; width:32.6%;border-style:none; margin:0.1em; background-color:#fff; display:flex; flex-direction:row;
justify-content: space-around">
  <a href="{{ url_for('todo.delete_task', id=task.id) }}"><input type='checkbox' class='checkbox'></input></a>
  <a href="{{ url_for('todo.task', id=task.id) }}"><p><b>{{ task.name }}</b></p> </a>
</div>

app/templates/todo/_task_display.html
<div class="card" style="height:100%; padding:1em; width:32.6%;border-style:none; margin:0.1em; background-color:#fff;">
  <a href="{{ url_for('todo.task', id=task.id) }}"><p><b>{{ task.name }}</b></p> </a>
  Posted {{ moment(task.timestamp).fromNow() }}.
	<div class="inline" style="justify-content:flex-start;margin-top:0.5em; align-content:flex-start;padding-bottom:0em;">
    <h1 style="font-size:5em; margin:0em;">{{task.completion_percent()}}</h1>
    <h1 style="margin:0em; font-size:2em; color:grey;">%</h1>
  </div>
	<sub-header style="justify-content:center; margin-bottom:0.1em;">complete</sub-header>
	<div class="progress" style="width:93%;height:0.5em; margin-top:0.3em; ">
	   <div class="progress-bar" role="progressbar" style="background-color:#000; width: {{ task.completion_percent() }}%"></div>
	</div>
  <a href="{{ url_for('todo.delete_task', id = task.id) }}">
    Delete</a>
</div>

app/templates/todo/task.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
	<div class="section">
	<a href="{{url_for('todo.tasks')}}">Back</a>
	<h1>{{ task.name }}</h1>
	<h4>{{ task.completion_percent() }} percent complete.</h4>
	<p>Posted a day ago.</p>
	<a href="">Edit Task</a>
	<div class="row">
			{{ wtf.quick_form(form) }}
    	</div>
	<hr>
	{% if task.n_subtasks>0 %}
		<h3>Subtasks</h3>
	    <form method="POST" action="">
		    {% for subtask in c_subtasks %}

		    <!-- Default unchecked -->
			<div class="custom-control custom-checkbox">
			    <input type="checkbox" class="custom-control-input" name="status_checkbox" value="{{ subtask.id }}" id="{{ subtask.id }}" checked>
			    <label class="custom-control-label" for="{{ subtask.id }}">{{ subtask.name }}</label>
			</div>
		    {% endfor %}
		    {% for subtask in uc_subtasks %}
		    	<div class="custom-control custom-checkbox">
			    <input type="checkbox" class="custom-control-input" name="status_checkbox" value={{ subtask.id }} id="{{ subtask.id }}" >
			    <label class="custom-control-label" for="{{ subtask.id }}" >{{ subtask.name }}</label>
			</div>
		    {% endfor %}
		<br>
		<input type="submit" name="submit" value="Check subtasks">
	     </form>
	{% endif %}
	</div>
{% endblock %}

app/templates/todo/tasks_home.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<div class="section" >
	<p>Today: {{ moment(today).format('LL') }}, {{ weekday }}</p>
	<h1>Tasks this week...</h1>
	<p>{{ days_left }} days left</p>

	{% if form %}
		<div class="subsection">
		    {{ wtf.quick_form(form) }}
		</div>
	{% endif %}
</div>
<div class="section">
	<h2>Daily tasks</h2>
</div>
		<div class = "grid-container" style="padding:0;">
		{% for task in daily_tasks %}
			{% include 'todo/_daily_task_display.html' %}
		{% endfor %}
		</div>

	<div class="section">
	<h2>Weekly tasks</h2>
	</div>
		<div class = "grid-container" style="padding:0;">
		{% for task in weekly_tasks %}
			{% include 'todo/_task_display.html' %}
		{% endfor %}
	</div>

	<div class="section">
	<h2>Challenge tasks</h2>
	</div>
		<div class = "grid-container" style="padding:0;">
		{% for task in challenge_tasks %}
			{% include 'todo/_challenge_task_display.html' %}
		{% endfor %}
	</div>

{% endblock %}